import { globalLocAssetCountsMinMax } from "./constants.js";

export const assetTypes = [
  { type: "Camera", description: "Outdoor security camera" },
  { type: "Camera", description: "Indoor security camera" },
  { type: "Camera", description: "PTZ surveillance camera" },
  { type: "Sensor", description: "Motion detector sensor" },
  { type: "Sensor", description: "Temperature monitoring sensor" },
  { type: "Alarm", description: "Emergency alarm system" },
  { type: "Alarm", description: "Fire alarm panel" },
  { type: "Access Control", description: "Biometric access reader" },
  { type: "Access Control", description: "RFID card reader" },
  { type: "Intercom", description: "Video intercom station" },
  { type: "Smoke Detector", description: "Photoelectric smoke detector" },
  {
    type: "Glass Break Sensor",
    description: "Acoustic glass break detector",
  },
  { type: "Floodlight", description: "Motion-activated floodlight" },
  { type: "Video Doorbell", description: "Smart video doorbell" },
  { type: "Engine", description: "V6 3.5L engine block" },
  { type: "Engine", description: "V8 5.0L engine assembly" },
  { type: "Transmission", description: "Automatic 6-speed transmission" },
  { type: "Transmission", description: "Manual 5-speed gearbox" },
  { type: "Brake System", description: "Hydraulic disc brake kit" },
  { type: "Brake System", description: "ABS brake control module" },
  { type: "Alternator", description: "120A alternator assembly" },
  { type: "Starter Motor", description: "12V starter motor" },
  { type: "Radiator", description: "Aluminum cooling radiator" },
  { type: "Battery", description: "12V lead-acid car battery" },
  { type: "Fuel Pump", description: "Electric fuel pump assembly" },
  { type: "Air Filter", description: "High-flow air filter" },
  { type: "Oil Filter", description: "Spin-on oil filter" },
  { type: "Spark Plugs", description: "Iridium spark plug set" },
  { type: "Suspension", description: "Front strut assembly" },
  { type: "Suspension", description: "Rear shock absorber" },
  { type: "Exhaust", description: "Catalytic converter" },
  { type: "Exhaust", description: "Muffler assembly" },
  { type: "Tire", description: "All-season radial tire" },
  { type: "Tire", description: "Performance summer tire" },
  { type: "Wheel", description: "17-inch alloy wheel" },
  { type: "Headlight", description: "LED headlight assembly" },
  { type: "Taillight", description: "LED tail lamp assembly" },
  { type: "Windshield", description: "Laminated safety windshield" },
  { type: "Side Mirror", description: "Power-adjust side mirror" },
  { type: "Bumper", description: "Front bumper cover" },
  { type: "Hood", description: "Steel hood panel" },
  { type: "Fender", description: "Front fender panel" },
  { type: "Door", description: "Front driver side door" },
  { type: "Seat", description: "Leather driver seat" },
  { type: "Steering Wheel", description: "Multi-function steering wheel" },
  { type: "Dashboard", description: "Instrument panel assembly" },
];

export const globalLocations = [
  { city: "Berlin", country: "Germany", coords: [52.52, 13.405] },
  { city: "Oakland", country: "USA", coords: [37.8044, -122.2711] },
  { city: "Philadelphia", country: "USA", coords: [39.9526, -75.1652] },
  { city: "Vancouver", country: "Canada", coords: [49.2827, -123.1207] },
  { city: "Singapore", country: "Singapore", coords: [1.3521, 103.8198] },
  { city: "Sydney", country: "Australia", coords: [-33.8688, 151.2093] },
  { city: "Tokyo", country: "Japan", coords: [35.6762, 139.6503] },
  { city: "Brasília", country: "Brazil", coords: [-15.8267, -47.9218] },
].sort((a, b) => a.city.localeCompare(b.city));

export const cityLocations = {
  Berlin: [
    {
      city: "Berlin",
      country: "Germany",
      neighborhood: "Mitte",
      address: "Alexanderplatz 1",
      coords: [52.5219, 13.4132],
    },
    {
      city: "Berlin",
      country: "Germany",
      neighborhood: "Kreuzberg",
      address: "Oranienstraße 1",
      coords: [52.502, 13.419],
    },
    {
      city: "Berlin",
      country: "Germany",
      neighborhood: "Prenzlauer Berg",
      address: "Kollwitzstraße 1",
      coords: [52.538, 13.424],
    },
    {
      city: "Berlin",
      country: "Germany",
      neighborhood: "Friedrichshain",
      address: "Boxhagener Platz 1",
      coords: [52.515, 13.454],
    },
    {
      city: "Berlin",
      country: "Germany",
      neighborhood: "Charlottenburg",
      address: "Kurfürstendamm 1",
      coords: [52.502, 13.333],
    },
    {
      city: "Berlin",
      country: "Germany",
      neighborhood: "Neukölln",
      address: "Karl-Marx-Straße 1",
      coords: [52.487, 13.439],
    },
    {
      city: "Berlin",
      country: "Germany",
      neighborhood: "Spandau",
      address: "Altstädter Ring 1",
      coords: [52.537, 13.199],
    },
  ],
  Brasilia: [
    {
      city: "Brasília",
      country: "Brazil",
      neighborhood: "Asa Norte",
      address: "1000 Norte St",
      coords: [-15.8267, -47.9218],
    },
    {
      city: "Brasília",
      country: "Brazil",
      neighborhood: "Asa Sul",
      address: "2000 Sul St",
      coords: [-15.832, -47.921],
    },
    {
      city: "Brasília",
      country: "Brazil",
      neighborhood: "Lago Sul",
      address: "3000 Lago Sul St",
      coords: [-15.85, -47.9],
    },
    {
      city: "Brasília",
      country: "Brazil",
      neighborhood: "Lago Norte",
      address: "4000 Lago Norte St",
      coords: [-15.81, -47.9],
    },
  ],
  Oakland: [
    {
      city: "Oakland",
      country: "USA",
      neighborhood: "Downtown",
      address: "123 Main St",
      coords: [37.8044, -122.2711],
    },
    {
      city: "Oakland",
      country: "USA",
      neighborhood: "Jack London Square",
      address: "456 Water St",
      coords: [37.798, -122.277],
    },
    {
      city: "Oakland",
      country: "USA",
      neighborhood: "Piedmont",
      address: "789 Piedmont Ave",
      coords: [37.824, -122.231],
    },
    {
      city: "Oakland",
      country: "USA",
      neighborhood: "Rockridge",
      address: "321 College Ave",
      coords: [37.844, -122.251],
    },
  ],
  Philadelphia: [
    {
      city: "Philadelphia",
      country: "USA",
      neighborhood: "Center City",
      address: "100 Market St",
      coords: [39.9526, -75.1652],
    },
    {
      city: "Philadelphia",
      country: "USA",
      neighborhood: "University City",
      address: "200 University Ave",
      coords: [39.952, -75.193],
    },
    {
      city: "Philadelphia",
      country: "USA",
      neighborhood: "Fishtown",
      address: "300 Frankford Ave",
      coords: [39.965, -75.143],
    },
    {
      city: "Philadelphia",
      country: "USA",
      neighborhood: "South Philadelphia",
      address: "400 Passyunk Ave",
      coords: [39.935, -75.165],
    },
    {
      city: "Philadelphia",
      country: "USA",
      neighborhood: "Northern Liberties",
      address: "500 N 2nd St",
      coords: [39.962, -75.149],
    },
  ],
  Vancouver: [
    {
      city: "Vancouver",
      country: "Canada",
      neighborhood: "Downtown",
      address: "100 Burrard St",
      coords: [49.2827, -123.1207],
    },
    {
      city: "Vancouver",
      country: "Canada",
      neighborhood: "Kitsilano",
      address: "200 West 4th Ave",
      coords: [49.268, -123.168],
    },
    {
      city: "Vancouver",
      country: "Canada",
      neighborhood: "Gastown",
      address: "300 Water St",
      coords: [49.283, -123.109],
    },
  ],
  Singapore: [
    {
      city: "Singapore",
      country: "Singapore",
      neighborhood: "Marina Bay",
      address: "10 Marina Blvd",
      coords: [1.283, 103.86],
    },
    {
      city: "Singapore",
      country: "Singapore",
      neighborhood: "Orchard Road",
      address: "20 Orchard Rd",
      coords: [1.305, 103.831],
    },
    {
      city: "Singapore",
      country: "Singapore",
      neighborhood: "Sentosa",
      address: "30 Sentosa Gateway",
      coords: [1.249, 103.83],
    },
  ],
  Sydney: [
    {
      city: "Sydney",
      country: "Australia",
      neighborhood: "CBD",
      address: "100 George St",
      coords: [-33.8688, 151.2093],
    },
    {
      city: "Sydney",
      country: "Australia",
      neighborhood: "Surry Hills",
      address: "200 Crown St",
      coords: [-33.884, 151.211],
    },
    {
      city: "Sydney",
      country: "Australia",
      neighborhood: "Newtown",
      address: "300 King St",
      coords: [-33.898, 151.183],
    },
    {
      city: "Sydney",
      country: "Australia",
      neighborhood: "Bondi",
      address: "400 Bondi Rd",
      coords: [-33.89, 151.274],
    },
    {
      city: "Sydney",
      country: "Australia",
      neighborhood: "Manly",
      address: "500 Manly Wharf",
      coords: [-33.798, 151.287],
    },
  ],
  Tokyo: [
    {
      city: "Tokyo",
      country: "Japan",
      neighborhood: "Shinjuku",
      address: "1-1-1 Shinjuku",
      coords: [35.6938, 139.7034],
    },
    {
      city: "Tokyo",
      country: "Japan",
      neighborhood: "Shibuya",
      address: "2-2-2 Shibuya",
      coords: [35.6581, 139.7016],
    },
    {
      city: "Tokyo",
      country: "Japan",
      neighborhood: "Akihabara",
      address: "3-3-3 Akihabara",
      coords: [35.7023, 139.7745],
    },
    {
      city: "Tokyo",
      country: "Japan",
      neighborhood: "Ginza",
      address: "4-4-4 Ginza",
      coords: [35.6717, 139.7645],
    },
    {
      city: "Tokyo",
      country: "Japan",
      neighborhood: "Asakusa",
      address: "5-5-5 Asakusa",
      coords: [35.7148, 139.7967],
    },
  ],
};

export const localLocations = [
  { name: "Warehouse A", coords: [0, 0] },
  { name: "Warehouse B", coords: [0, 0] },
  { name: "Warehouse C", coords: [0, 0] },
  { name: "Warehouse D", coords: [0, 0] },
  { name: "Administration A", coords: [0, 0] },
  { name: "Administration B", coords: [0, 0] },
  { name: "Administration C", coords: [0, 0] },
  { name: "Repair Shop A", coords: [0, 0] },
  { name: "Repair Shop B", coords: [0, 0] },
  { name: "Maintenance Area A", coords: [0, 0] },
  { name: "Maintenance Area B", coords: [0, 0] },
];

export const statuses = [
  "Active",
  "Inactive",
  "Under Maintenance",
  "Decommissioned",
  "Lost",
  "In Repair",
  "New",
  "Retired",
];

// For each global location, come up with a number of total assets that would be "seen" there, ranging from 150 to 3000
export const globalAssetCounts = globalLocations.map((loc) => {
  const randomAssetCount = () => {
    const [min, max] = globalLocAssetCountsMinMax;
    return Math.floor(Math.random() * (max - min + 1)) + min;
  };
  const count = randomAssetCount();
  return { location: loc.city, coords: loc.coords, count };
});
