export const assetTypes = [
  { type: "Camera", description: "Outdoor security camera" },
  { type: "Camera", description: "Indoor security camera" },
  { type: "Camera", description: "PTZ surveillance camera" },
  { type: "Sensor", description: "Motion detector sensor" },
  { type: "Sensor", description: "Temperature monitoring sensor" },
  { type: "Alarm", description: "Emergency alarm system" },
  { type: "Alarm", description: "Fire alarm panel" },
  { type: "Access Control", description: "Biometric access reader" },
  { type: "Access Control", description: "RFID card reader" },
  { type: "Intercom", description: "Video intercom station" },
  { type: "Smoke Detector", description: "Photoelectric smoke detector" },
  {
    type: "Glass Break Sensor",
    description: "Acoustic glass break detector",
  },
  { type: "Floodlight", description: "Motion-activated floodlight" },
  { type: "Video Doorbell", description: "Smart video doorbell" },
  { type: "Engine", description: "V6 3.5L engine block" },
  { type: "Engine", description: "V8 5.0L engine assembly" },
  { type: "Transmission", description: "Automatic 6-speed transmission" },
  { type: "Transmission", description: "Manual 5-speed gearbox" },
  { type: "Brake System", description: "Hydraulic disc brake kit" },
  { type: "Brake System", description: "ABS brake control module" },
  { type: "Alternator", description: "120A alternator assembly" },
  { type: "Starter Motor", description: "12V starter motor" },
  { type: "Radiator", description: "Aluminum cooling radiator" },
  { type: "Battery", description: "12V lead-acid car battery" },
  { type: "Fuel Pump", description: "Electric fuel pump assembly" },
  { type: "Air Filter", description: "High-flow air filter" },
  { type: "Oil Filter", description: "Spin-on oil filter" },
  { type: "Spark Plugs", description: "Iridium spark plug set" },
  { type: "Suspension", description: "Front strut assembly" },
  { type: "Suspension", description: "Rear shock absorber" },
  { type: "Exhaust", description: "Catalytic converter" },
  { type: "Exhaust", description: "Muffler assembly" },
  { type: "Tire", description: "All-season radial tire" },
  { type: "Tire", description: "Performance summer tire" },
  { type: "Wheel", description: "17-inch alloy wheel" },
  { type: "Headlight", description: "LED headlight assembly" },
  { type: "Taillight", description: "LED tail lamp assembly" },
  { type: "Windshield", description: "Laminated safety windshield" },
  { type: "Side Mirror", description: "Power-adjust side mirror" },
  { type: "Bumper", description: "Front bumper cover" },
  { type: "Hood", description: "Steel hood panel" },
  { type: "Fender", description: "Front fender panel" },
  { type: "Door", description: "Front driver side door" },
  { type: "Seat", description: "Leather driver seat" },
  { type: "Steering Wheel", description: "Multi-function steering wheel" },
  { type: "Dashboard", description: "Instrument panel assembly" },
];

export const locations = [
  "Main Entrance",
  "Lobby",
  "Parking Lot",
  "Warehouse",
  "Office 101",
  "Conference Room",
  "Backyard",
  "Rooftop",
  "Hallway A",
  "Loading Dock",
];

export const statuses = [
  "Active",
  "Inactive",
  "Under Maintenance",
  "Decommissioned",
  "Lost",
  "In Repair",
  "New",
  "Retired",
];
